package mustafa;

public class Q3 {

	public static void main(String[] args) {
		/*
		 *  Q3:Java bytecode is stored in .class which is unexecutable
		 *  and this is where Java’s platform independence comes from
		 *  bytecodes generated by one platform can be executed in 
		 *  another platform.
		 */
		
	}

}
